name: coderefinery
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python>3.7
  - click=7.1.2
  - ipywidgets=7.6.3
  - jupyterlab=3.0.14
  - jupyterlab-git=0.30.0
  - matplotlib=3.4.1
  - numpy=1.20.2
  - pandas=1.2.4
  - pytest=6.2.3
  - seaborn=0.11.1
  - snakemake-minimal=6.2.1
  - sphinx=3.5.4
  - sphinx_rtd_theme=0.5.2
  - pip
#  - pip:
#    - jupyterlab-github==2.0.0
